siteName: A-Level Retakes
title: A-Level & GCSE Retakes
author: David White
url: https://a-level-retakes.com
poweredByOne: Kabooly
poweredByTwo: Arragon Affiliates
poweredByOneUrl: https://kabooly.com/?utm_source=a-level-retakes&utm_medium=referral&utm_campaign=footer-link
poweredByTwoUrl: https://arragonaffiliates.com/?utm_source=a-level-retakes&utm_medium=referral&utm_campaign=footer-link
description: A-level retakes, courses, and private tuition
type: website
logoAlt: A-level retakes Logo
logoUrl: /static/img/logo.png
